apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-api
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: AzureStorageAccountKey
            - name: AzureStorageAccountName
            - name: AzureStorageEnabled
              value: "False"
            - name: ConnectionString
              value: Server=docker.for.mac.localhost,5433;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
            - name: EventBusConnection
              value: rabbitmq
            - name: EventBusPassword
            - name: EventBusUserName
            - name: GRPC_PORT
              value: "81"
            - name: OrchestratorType
            - name: PATH_BASE
              value: /catalog-api
            - name: PORT
              value: "80"
            - name: PicBaseUrl
              value: http://docker.for.mac.localhost:5202/c/api/v1/catalog/items/[0]/pic/
            - name: UseCustomizationData
              value: "True"
          image: eshop/catalog.api:linux-latest
          name: catalog-api
          ports:
            - containerPort: 80
            - containerPort: 81
          resources: {}
      restartPolicy: Always
status: {}
