apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-webshoppingagg
  name: eshop-webshoppingagg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-webshoppingagg
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: eshop-webshoppingagg
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: BasketUrlHC
              value: http://basket-api/hc
            - name: CatalogUrlHC
              value: http://catalog-api/hc
            - name: IdentityUrlExternal
              value: http://:5105
            - name: IdentityUrlHC
              value: http://identity-api/hc
            - name: OrderingUrlHC
              value: http://ordering-api/hc
            - name: PaymentUrlHC
              value: http://payment-api/hc
            - name: urls__basket
              value: http://basket-api
            - name: urls__catalog
              value: http://catalog-api
            - name: urls__grpcBasket
              value: http://basket-api:81
            - name: urls__grpcCatalog
              value: http://catalog-api:81
            - name: urls__grpcOrdering
              value: http://ordering-api:81
            - name: urls__identity
              value: http://identity-api
            - name: urls__orders
              value: http://ordering-api
          image: eshop/webshoppingagg:linux-latest
          name: eshop-webshoppingagg
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
