apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-basket-api
  name: eshop-basket-api
spec:
  ports:
    - name: "5103"
      port: 5103
      targetPort: 80
    - name: "9103"
      port: 9103
      targetPort: 81
  selector:
    io.kompose.service: eshop-basket-api
status:
  loadBalancer: {}
