apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nosqldata
  name: nosqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nosqldata
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nosqldata
    spec:
      containers:
        - image: mongo
          name: nosqldata
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: eshop-nosqldata
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/marshinov/Work/education/max-arshinov/eShopOnContainers/src
          name: eshop-nosqldata
status: {}
