apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-api
  name: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: payment-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: EventBusConnection
              value: rabbitmq
            - name: EventBusPassword
            - name: EventBusUserName
            - name: OrchestratorType
            - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
              value: Verbose
            - name: Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling
              value: Verbose
          image: eshop/payment.api:linux-latest
          name: payment-api
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
