apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: seq
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
          image: datalust/seq:latest
          name: seq
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
