apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webhooks-api
  name: webhooks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhooks-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webhooks-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ConnectionString
              value: Server=sqldata;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass@word
            - name: EventBusConnection
              value: rabbitmq
            - name: EventBusPassword
            - name: EventBusUserName
            - name: IdentityUrl
              value: http://identity-api
            - name: IdentityUrlExternal
              value: http://docker.for.mac.localhost:5105
          image: eshop/webhooks.api:linux-latest
          name: webhooks-api
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
